runtime: python39

entrypoint: gunicorn app:server

instance_class: F1

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.7

env_variables:
  BUCKET_NAME: "senior-project-457222.appspot.com"
  IS_LOCAL: false

handlers:
  - url: /assets
    static_dir: assets
  - url: /.*
    script: auto
